Repository Vimall03/Alimento, pull requests merged in 2024-10, with the labels that each got.

#10 #Add Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#23 password complexity
  .vscode/settings.json
  user_login.php
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level1

#30 Create nutri.html issue no # 27
  nutri.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#33 Fix issue #29: I have made the email functionality work in the contact form.
  contact.php
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level2

#37 added dark mode option
  images/favicons/sun.png
  index.html
  js/js/script.js
  main.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#39 Change UI for Vendor's Home Page
  vendor/add_menu.php
  vendor/edit_menu.php
  vendor/home.php
Labels: hacktoberfest-accepted, gssoc-ext, level2

#45 Additon of All Contributors | Issue #36
  readme.md
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level1

#58 fixed the dark mode issue and issue#56
  index.html
  main.css
  menu.php
  pin_search.php
  track_order.php
Labels: hacktoberfest-accepted, gssoc-ext, level2

#59 Add contribution.md
  Contribution.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#65 Fix reg/login validation
  email_verify.php
  main.css
  user_login.php
  user_signup.php
Labels: hacktoberfest-accepted, gssoc-ext, level2

#66 Chatbot added
  checkout.php
  email_verify.php
  home.php
  index.html
  order_success.php
  track_order.php
  user_signup.php
Labels: hacktoberfest-accepted, gssoc-ext, level1

#68 Changes have been made
  about.css
  about.html
  about_b_g.jpg
  about_background.jpg
  community_alimento.jpg
  fb_alimento.png
  index.html
  innovation_alimento.jpg
  insta_icon.png
  quality_alimento.jpg
  twitter_icon.png
Labels: hacktoberfest-accepted, gssoc-ext, level1

#80 Fixed Payment gateway - Razorpay
  checkout.php
  menu.php
  pay.php
  verify.php
Labels: level2

#89 Update footer
  index.html
  main.css
  styles.css
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level1

#92 Added 4 New Files: profile.php, update_profile.php, change_password.php, orders.php and Changed Database Schema
  Contribution.md
  change_password.php
  edit_profile.php
  home.php
  homemadedb.sql
  images/default_profile.png
  orders.php
  profile.php
Labels: hacktoberfest-accepted, gssoc-ext, level3

#94 added scroll to top
  index.html
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level1

#95 enhanced contact us
  index.html
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level1

#100 New track order page
  new_track_order.css
  new_track_order.php
  verify.php
Labels: hacktoberfest-accepted, gssoc-ext, level2

#99 Added: FAQ Section
  index.html
  main.css
Labels: hacktoberfest-accepted, gssoc-ext, level1

#120 ✨contributors page added.✨
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  index.html
Labels: hacktoberfest-accepted, gssoc-ext, level1

#125 multi language support system added.
  edit_profile.php
  email_verify.php
  home.php
  index.html
  menu.php
  new_track_order.php
  order_success.php
  orders.php
  pin_search.php
  profile.php
  track_order.php
  user_login.php
  user_signup.php
Labels: hacktoberfest-accepted, gssoc-ext

#137 Added pr-checker
  .github/workflows/pr-checker.yml
Labels: hacktoberfest-accepted, gssoc-ext, level2

#141 changed navbar design
  change_password.php
  checkout.php
  edit_profile.php
  home.php
  index.php
  main.css
  menu.php
  new_track_order.php
  orders.php
  output.css
  profile.php
Labels: hacktoberfest-accepted, gssoc-ext, level2

#144 Updated bot #116
  chatbot.css
  chatbot.html
  chatbot.js
  chatboticon.png
  icons8-message-bot-64.png
  index.php
Labels: hacktoberfest-accepted, gssoc-ext, level2

#150 Update Contribution.md
  Contribution.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#130 Main
  customisable_meal_options/asstes/css/style.css
  customisable_meal_options/asstes/js/script.js
  customisable_meal_options/customize_meal.php
  customisable_meal_options/includes/db.php
  customisable_meal_options/index.php
  customisable_meal_options/process_order.php
  homemadedb.sql
Labels: hacktoberfest-accepted, gssoc-ext

#151 Fixing pr cheker!
  .github/workflows/pr-checker.yml
  .github/workflows/pr_validation.yaml
Labels: hacktoberfest-accepted, gssoc-ext, level2

#165 Update readme.md Added Stargazers and Forkers section to readme.md
  readme.md
Labels: hacktoberfest-accepted, gssoc-ext, level1

#168 enhanced ui of users login and signup
  email_verify.php
  images/login.png
  images/signup.png
  output.css
  user_login.php
  user_signup.php
  vendor/email_verify.php
Labels: hacktoberfest-accepted, gssoc-ext
